### ISSUE TITLE
Broken link to guide

### ISSUE THREAD

**Issue by tv42** [nogula/tufte-memo#1]
https://github.com/nogula/tufte-memo/blob/80bc7cf7e0239491609d87e2ef8d4b9b282603ce/README.md#L4

links to

https://github.com/nogula/tufte-memo/blob/main/template/main.pdf

but you don't have the generated file in the repository

https://github.com/nogula/tufte-memo/tree/main/template

**Comment by nogula** [comment]
@tv42 thank you kindly for creating the issue. I've generated the file. For reference, it is the same file that is generated by the default template.
